#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <mpi.h>

const int num_iter_per_proc = 10 * 1000 * 1000;

int main() {
  // MPI_Init: Starts the MPI environment. Before this line, code runs serially; after this, the code is technically "parallel" (though all processes execute the same instructions).
  MPI_Init(NULL, NULL);
    
  int rank;
  int num_procs;
  
  // MPI_Comm_rank: Each process asks, "Who am I?" The result (rank) is a unique ID (0, 1, 2, etc.).
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  // MPI_Comm_size: Each process asks, "How many of us are there?" The result is stored in num_procs.
  MPI_Comm_size(MPI_COMM_WORLD, &num_procs);

  // + rank: By adding the rank, you ensure that every process has a unique seed.
  srand(time(NULL) + rank);
    
  double x, y;
  int count = 0;
  for (int i=0; i<num_iter_per_proc; i++) {
    x = ((double) rand()) / RAND_MAX;
    y = ((double) rand()) / RAND_MAX;
    if ((x*x) + (y*y) <= 1.0) {
      count++;
    }
  }

  /*
    This is the most important MPI function in this code. It gathers the partial results.

    - &count (Send Buffer): The local variable each process wants to contribute.
    - &sum (Receive Buffer): Where the final result will be stored (only relevant for the "root" process).
    - MPI_SUM: The operation to perform. MPI will take the count from Rank 0, Rank 1, Rank 2... and add them all together.
    - 0 (Root): The rank ID that receives the final result. All other ranks will have garbage or 0 in their sum variable, but Rank 0 will hold the total.
  */
  int sum;
  MPI_Reduce(&count, &sum, 1, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);
    
  if (rank == 0) {
    double pi = (4.0*sum) / (num_iter_per_proc*num_procs);
    printf("Pi = %f\n", pi);
  }
  
  // Shuts down the MPI environment. No MPI functions can be called after this.
  MPI_Finalize();
  return 0;
}

/*
  1. Arithmetic Operations
  A. Finding the Maximum (MPI_MAX) or Minimum (MPI_MIN)
    Used to find the global highest or lowest value among all processes (e.g., maximum error, highest temperature).

    double local_max = get_local_maximum();
    double global_max;
    // Find the single highest value across all processes
    MPI_Reduce(&local_max, &global_max, 1, MPI_DOUBLE, MPI_MAX, 0, MPI_COMM_WORLD);

  B. Global Product (MPI_PROD)
    Used for calculating factorials or combined probabilities.

    int local_val = 5;
    int global_product;
    // Calculates local_val_P0 * local_val_P1 * ...
    MPI_Reduce(&local_val, &global_product, 1, MPI_INT, MPI_PROD, 0, MPI_COMM_WORLD);

  2. Logical Operations (Consensus)
  A. Check if EVERYONE is ready (MPI_LAND - Logical AND)
    Example: "Did every process finish its initialization successfully?"

    int local_success = (init_everything() == 0); // 1 if true, 0 if false
    int global_success;
    // Result is 1 only if ALL processes send 1. If anyone sends 0, result is 0.
    MPI_Reduce(&local_success, &global_success, 1, MPI_INT, MPI_LAND, 0, MPI_COMM_WORLD);
    if (rank == 0 && global_success) {
        printf("System stable. Starting simulation.\n");
    }

    B. Check if ANYONE found the target (MPI_LOR - Logical OR)
      Example: "Did any process find the password/needle in the haystack?"

      int found_target = search_local_data(); // 1 if found, 0 if not
      int anyone_found;
      // Result is 1 if AT LEAST ONE process sends 1.
      MPI_Reduce(&found_target, &anyone_found, 1, MPI_INT, MPI_LOR, 0, MPI_COMM_WORLD);
      if(anyone_found == ...) {
        ...
      }

    3. Value and Location (MPI_MAXLOC / MPI_MINLOC)
      This answers the question: "What is the maximum value, AND which rank has it?" This is widely used in algorithms like "Leader Election" (the process with the highest random number becomes the leader).
      Requirement: You must use a struct-like pair datatype (e.g., MPI_DOUBLE_INT or MPI_FLOAT_INT).

      struct {
          double value;
          int    rank;
      } local_data, global_result;

      local_data.value = ((double)rand()) / RAND_MAX;
      local_data.rank  = rank; // I am this rank
      // MPI finds the max value, and keeps the rank associated with it
      MPI_Reduce(&local_data, &global_result, 1, MPI_DOUBLE_INT, MPI_MAXLOC, 0, MPI_COMM_WORLD);
      if (rank == 0) {
          printf("Highest value %f was generated by Rank %d\n", 
                global_result.value, global_result.rank);
      }
    
      This is one of the most useful but slightly complex concepts in MPI because it deals with pairs of data rather than single numbers.

      - The Problem: "Who won?"
      If you use standard MPI_MAX, you get the maximum value, but you lose the information about where that value came from.
          MPI_MAX: "The highest temperature measured was 100°C." (Unknown location).
          MPI_MAXLOC: "The highest temperature was 100°C, and it was measured by Sensor #5."
      - The Data Structure (The "Pair")
      To solve this, MPI needs to move two pieces of information together as a single unit:
          The Value (e.g., the temperature, the random number).
          The Index (e.g., the rank, the array index).
      
      When you pass this struct to MPI_Reduce, you tell MPI to treat it as a special combined type: MPI_DOUBLE_INT.
      MPI knows this type consists of one double followed by one int.

    4. Vector Reduction (Element-wise)
      You are not limited to reducing a single integer (count=1). You can reduce arrays. MPI will perform the operation index-by-index.
      Example: Summing two vectors (physics forces, matrix rows).

      // Each process has an array of 3 numbers
      int local_vec[3] = {1, 2, 3}; 
      int global_vec[3];
      // MPI performs:
      // global[0] = sum(all local_vec[0])
      // global[1] = sum(all local_vec[1]) ...
      MPI_Reduce(local_vec, global_vec, 3, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);
*/